CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,

uuid UUID NOT NULL UNIQUE,

name VARCHAR(255) NOT NULL,

email VARCHAR(255) NOT NULL UNIQUE,

password TEXT NOT NULL,

role_id BIGINT NOT NULL,

created_at TIMESTAMP NOT NULL DEFAULT NOW(),

updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

CONSTRAINT fk_users_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id)
    ON DELETE RESTRICT

);